#!/bin/bash
cat LICENCE
git submodule init
git submodule update

if [ ! -e /usr/bin/node ]  && [ ! -e /usr/local/bin/node ] && [ ! -e /usr/local/bin/node ] && [ ! -e /usr/sbin/node ];
then
    echo 'node.js is not installed. Please install it before running install.sh.'
    exit 1
fi
if [ ! -e /usr/bin/npm ] && [ ! -e /usr/local/bin/npm ] && [ ! -e /usr/sbin/npm ];
then
    echo 'npm is not installed. Please install it before running install.sh'
    exit 1
fi

npm install googlemaps feedparser node-units tvdb crypto-js method-override 500px process async wordnik node-uuid underscore request sandbox express moment-timezone moment jade databank databank-redis ent passport passport-local password-hash connect-flash 

cd public/
wget https://github.com/twbs/bootstrap/releases/download/v3.3.2/bootstrap-3.3.2-dist.zip
unzip bootstrap-3.3.2-dist.zip
mv bootstrap-3.3.2-dist bootstrap
rm bootstrap-3.3.2-dist.zip

mkdir d3
cd d3
wget https://github.com/mbostock/d3/releases/download/v3.5.5/d3.zip
unzip d3.zip
rm d3.zip

cd ../..

if [ ! -f config.json ];
then
    echo 'Creating configuration file...'
    cp config.json.sample config.json
    $EDITOR config.json # Open config file with EDITOR variable, but if not available:
    if [[ $? != 0 ]]; then vim config.json; fi # Find the return code from previous command, if failed then use vim to edit.
fi

read -p "Setup complete. Run dbot now? [y/N]"
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo 'Okay. To run the bot, use "node run.js"'
    exit
fi
node run.js

